version: '2'
services:
  mysql5.5:
    build: .
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data:/docker-entrypoint-initdb.d
