spring:
  application:
    name: demo-service-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.2:8761/eureka}
logging:
  level:
    com.demo.service.client.WeatherServiceHealthCheckClient: DEBUG